export const categoryNames = {
  sports: "Sports et Loisirs",
  fashion: "Mode",
  lighting: "Luminaires et Éclairage",
  software: "Logiciels",
  books: "Livres",
  videogames: "Jeux vidéo",
  toys: "Jeux et Jouets",
  "lawn-garden": "Jardin",
  "musical-instruments": "Instruments de musique et Sono",
  computers: "Informatique",
  hpc: "Hygiène et Santé",
  electronics: "High-Tech",
  appliances: "Gros électroménager",
  officeproduct: "Fournitures de bureau",
  grocery: "Epicerie",
  dvd: "DVD et Blu-ray",
  kitchen: "Cuisine et Maison",
  industrial: "Commerce, Industrie et Science",
  "climate-pledge": "Engagement en faveur du climat",
  music: "CD et Vinyles",
  hi: "Bricolage",
  "digital-text": "Kindle",
  "gift-cards": "Cartes cadeaux",
  beauty: "Beauté et Parfum",
  automotive: "Auto et Moto",
  "mobile-apps": "Applis et Jeux",
  "amazon-devices": "Appareils Amazon et Accessoires",
  "pet-supplies": "Animalerie",
}
